In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("shapes.csv")
df.head()

,area,perimeter,sides,compactness,shape
0,60.54,45.31,3,0.3324,triangle
1,106.77,42.60,4,0.7382,rectangle
2,149.13,43.98,0,0.9745,circle
3,90.73,47.11,3,0.4693,triangle
4,36.40,29.52,3,0.5290,triangle


In [8]:
X1=df['sides']
X2=df['compactness']
X=np.concatenate((X1,X2))
y=df["shape"]
X = X.reshape(-1, 1)

In [35]:
def labelEncoder(y):
    classes = np.unique(y)
    class_to_index = {cls: idx for idx, cls in enumerate(classes)}
    y_encoded = np.array([class_to_index[label] for label in y])
    return y_encoded

In [36]:
def softmax(X,y):
    X = np.hstack((np.ones((X.shape[0], 1)), X))
    theta=np.zeros((X.shape[1], len(np.unique(y))))
    for i in range(100):
        for j in range(len(y)):
            z=X[j]@theta
            z=z-np.max(z)
            p=np.exp(z)/np.sum(np.exp(z))
            y_target = np.zeros(theta.shape[1])  
            y_target[y[j]] = 1.0
            J = np.outer(X[j], p - y_target)
            theta=theta-J
    return theta

In [37]:
y=labelEncoder(y)
a=softmax(X,y)
print(a)

[[ 17.28272355 -27.45359588  10.17087233]
 [ -7.23917433   9.05630839  -1.81713405]]


In [40]:
m=int(input("Enter the number of sides: "))
z_n=float(input("Enter the compactness: "))
x=np.array([[m,z_n]])
z = x @ a
p=np.exp(z)/np.sum(np.exp(z))
idx=np.argmax(p)
classes=["Triangle", "Circle",  "rectangle" ]
shape=classes[idx]
print(f"The predicted shape is: {shape}")


The predicted shape is: rectangle


In [34]:
classes

array([0, 1, 2])